### PR TITLE
Update to version 0.6.1

### PR DESCRIPTION
**Pull request by sameer-google**
Summary of Changes
This PR updates the submodule to pull the latest changes of a stable release from the [upstream repository](https://github.com/pyasn1/pyasn1). The update ensures compatibility with Python 3.12.

How Changes Were Made
- The submodule was updated by pulling the latest code from the upstream repository and squashing into a single commit as done previosly.
 - No manual changes were made to the submodule's codebase.
 
Reason for the Update
- This module has experienced breakages due to warnings about [invalid escape sequence](https://docs.python.org/dev/whatsnew/3.12.html#other-language-changes) introduced in python 3.12.
- The update addresses compatibility issues with Python 3.12 and brings the submodule up-to-date with the upstream repository's latest features and fixes.

Commit Picked
- Picked latest [stable release 0.6.1](https://github.com/pyasn1/pyasn1/releases/tag/v0.6.1)

### CODE REVIEW

**Comment by sushantkhanna** [comment]
Could you please provide more detailed descriptions clarifying what the change is about, did you do manual changes or was it through submodule update, if you did any manual changes then why and the details for the same.

**Comment by sameer-google** [comment]
> Could you please provide more detailed descriptions clarifying what the change is about, did you do manual changes or was it through submodule update, if you did any manual changes then why and the details for the same.

Provided detailed description, all the changes are from upstream repository, no manual changes are done.

**Comment by sushantkhanna** [comment]
Could you please also mention if this was picked up from a specific release for posterity ?
If it was from a specific commit, then that would show up on Github anway.

**Review by sushantkhanna — APPROVED** [review]

**Comment by sameer-google** [comment]
> Could you please also mention if this was picked up from a specific release for posterity ? If it was from a specific commit, then that would show up on Github anway.

Updated description with commit picked.

**Pull request merged**
